- name: "Tower Inventory Test"
  hosts: 127.0.0.1
  gather_facts: no

  tasks:
    - name: Add tower inventory
      tower_host:
        name: "Tower Host Test"
        description: "Just Host Test"
        inventory: "Tower Inventory Test"
        state: present # absent = delete
        tower_config_file: "/var/lib/awx/.tower_cli.cfg"
        variables: {host: real}
