- name: "Tower Inventory Test"
  hosts: local
  gather_facts: no

  tasks:
    - name: Add tower inventory
      tower_inventory:
        name: "Tower Inventory Test"
        description: "Just Test"
        organization: "Default"
        state: present # absent = delete
        #tower_config_file: "/var/lib/awx/.tower_cli.cfg"

